<?php

namespace Kiwi\Core\AdminDcat\Extend\Form;

use Dcat\Admin\Admin;
use Dcat\Admin\Form\Field;

class CKEditor2 extends Field
{
	public static $js = [
		'/vendor/dcat-admin-extensions/ckeditor/ckeditor.js',
	];

	protected $view = 'kiwi::admin.dcat.ckeditor2';

	public function render()
	{
		$config = (array)config("admin.extensions.ckeditor.config");

		$config = json_encode(array_merge($config, $this->options));

		$this->script = <<<EOT
CKEDITOR.replace(document.querySelector('textarea'), $config);
EOT;

		return parent::render(); // TODO: Change the autogenerated stub
	}
}
